# Generated by Django 2.0.6 on 2018-06-30 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_disaster', models.CharField(max_length=100)),
                ('latitude', models.CharField(default='18.910334', max_length=50)),
                ('longitude', models.CharField(default='72.810383', max_length=50)),
                ('level', models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Hospitals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.CharField(max_length=50)),
                ('longitude', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_no', models.CharField(max_length=10)),
                ('latitude', models.CharField(default='18.910334', max_length=50)),
                ('longitude', models.CharField(default='72.810383', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hospitals', to=settings.AUTH_USER_MODEL)),
                ('users_recieving_help', models.ManyToManyField(blank=True, null=True, related_name='hospitals_helping', to='app.Victim')),
            ],
        ),
        migrations.AddField(
            model_name='disaster',
            name='hospitals_associated',
            field=models.ManyToManyField(related_name='hospitals_disaster', to='app.HospitalUser'),
        ),
        migrations.AddField(
            model_name='disaster',
            name='users_associated',
            field=models.ManyToManyField(related_name='users_disaster', to='app.Victim'),
        ),
    ]
