# Generated by Django 2.0.6 on 2018-06-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180630_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='victim',
            name='type_of_help',
            field=models.CharField(choices=[('Food', 'Food'), ('Shelter', 'Shelter'), ('Crowdfunding', 'Crowdfunding')], default='Food', max_length=50),
        ),
        migrations.AlterField(
            model_name='disaster',
            name='level',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=1, max_length=5),
        ),
    ]
